import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import { fileURLToPath } from "node:url";

export default defineConfig({
  plugins: [react()],
  resolve: {
    tsconfigPaths: true,
    alias: {
      // `import "server-only"` throws outside an RSC build; stub it to an
      // empty module so server-only libs can be unit-tested in jsdom.
      "server-only": fileURLToPath(new URL("./vitest/server-only-stub.ts", import.meta.url)),
    },
  },
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./vitest/setup.ts"],
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
    clearMocks: true,
    restoreMocks: true,
    coverage: {
      provider: "v8",
      reporter: ["text", "text-summary", "lcov", "html"],
      reportsDirectory: "./coverage",
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.{test,spec}.{ts,tsx}",
        "src/types/**", // generated by openapi-typescript
        "src/components/ui/**", // vendored shadcn/base-ui primitives
        "src/app/**/layout.tsx",
        "src/app/**/page.tsx",
        "src/app/**/error.tsx",
        "src/app/{icon,apple-icon,opengraph-image,twitter-image}.tsx",
      ],
    },
  },
});
